// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScientificJournal.DataAccess.Context;

#nullable disable

namespace ScientificJournal.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731065455_AddReviewReportCategories")]
    partial class AddReviewReportCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.AdminState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("json_value");

                    b.Property<string>("StateKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("state_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("StateKey")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("admin_states", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.AdminSupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("status");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ticket_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("admin_support_tickets", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("affiliation");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Bookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("PublicationId")
                        .HasColumnType("int")
                        .HasColumnName("publication_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.HasIndex("UserId");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("FollowTargetId")
                        .HasColumnType("int")
                        .HasColumnName("follow_target_id");

                    b.Property<string>("FollowTargetName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_target_name");

                    b.Property<string>("FollowType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("follows", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ISSNOnline")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("issn_online");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("publisher");

                    b.HasKey("Id");

                    b.HasIndex("ISSNOnline")
                        .IsUnique();

                    b.ToTable("journals", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NormalizedTerm")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("normalized_term");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("term");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedTerm")
                        .IsUnique();

                    b.ToTable("keywords", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("acknowledged_at");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("delivery_status");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notification_type");

                    b.Property<int?>("PublicationId")
                        .HasColumnType("int")
                        .HasColumnName("publication_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_at");

                    b.Property<string>("Route")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("route");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("PublicationId");

                    b.HasIndex("UserId");

                    b.HasIndex("DeliveryStatus", "ScheduledAt", "NextAttemptAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abstract");

                    b.Property<int>("CitationCount")
                        .HasColumnType("int")
                        .HasColumnName("citation_count");

                    b.Property<string>("DOI")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("doi");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsOriginal")
                        .HasColumnType("bit")
                        .HasColumnName("is_original");

                    b.Property<int?>("JournalId")
                        .HasColumnType("int")
                        .HasColumnName("journal_id");

                    b.Property<string>("MongoMetadataId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mongo_metadata_id");

                    b.Property<string>("SourceApi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_api");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_url");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("synced_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("publication_year");

                    b.HasKey("Id");

                    b.HasIndex("DOI")
                        .IsUnique();

                    b.HasIndex("JournalId");

                    b.ToTable("publications", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationAuthor", b =>
                {
                    b.Property<int>("PublicationId")
                        .HasColumnType("int")
                        .HasColumnName("publication_id");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<int>("AuthorOrder")
                        .HasColumnType("int")
                        .HasColumnName("author_order");

                    b.HasKey("PublicationId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("publication_authors", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationKeyword", b =>
                {
                    b.Property<int>("PublicationId")
                        .HasColumnType("int")
                        .HasColumnName("publication_id");

                    b.Property<int>("KeywordId")
                        .HasColumnType("int")
                        .HasColumnName("keyword_id");

                    b.HasKey("PublicationId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("publication_keywords", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CredibilityRating")
                        .HasColumnType("int")
                        .HasColumnName("credibility_rating");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("is_hidden");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("moderated_at");

                    b.Property<string>("ModerationReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("moderation_reason");

                    b.Property<string>("ModerationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("visible")
                        .HasColumnName("moderation_status");

                    b.Property<string>("PublicationAbstract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("publication_abstract");

                    b.Property<string>("PublicationAuthors")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("publication_authors");

                    b.Property<string>("PublicationDoi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("publication_doi");

                    b.Property<string>("PublicationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("publication_key");

                    b.Property<string>("PublicationSource")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("publication_source");

                    b.Property<string>("PublicationTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("publication_title");

                    b.Property<string>("PublicationUrl")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)")
                        .HasColumnName("publication_url");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int")
                        .HasColumnName("publication_year");

                    b.Property<int>("ReportCount")
                        .HasColumnType("int")
                        .HasColumnName("report_count");

                    b.Property<string>("ReviewerRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("reviewer_role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PublicationKey")
                        .IsUnique();

                    b.ToTable("publication_reviews", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationReviewModerationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("ModeratorUserId")
                        .HasColumnType("int")
                        .HasColumnName("moderator_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("publication_review_moderation_events", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationReviewReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<int>("ReporterUserId")
                        .HasColumnType("int")
                        .HasColumnName("reporter_user_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("ReviewId", "ReporterUserId")
                        .IsUnique();

                    b.ToTable("publication_review_reports", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("change_type");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("PublicationId")
                        .HasColumnType("int")
                        .HasColumnName("publication_id");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("snapshot_json");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("PublicationId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("publication_versions", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at");

                    b.Property<int?>("RecordsSynced")
                        .HasColumnType("int")
                        .HasColumnName("records_synced");

                    b.Property<string>("SourceApi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_api");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int?>("TriggeredByUserId")
                        .HasColumnType("int")
                        .HasColumnName("triggered_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredByUserId");

                    b.ToTable("sync_logs", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.SystemEventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("actor");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("event_code");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Method")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("path");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("status_code");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Category", "Level");

                    b.ToTable("system_event_logs", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.TrendingMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("calculated_at");

                    b.Property<int>("KeywordId")
                        .HasColumnType("int")
                        .HasColumnName("keyword_id");

                    b.Property<int>("PublicationCount")
                        .HasColumnType("int")
                        .HasColumnName("publication_count");

                    b.Property<decimal?>("TrendingScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("trending_score");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId", "Year")
                        .IsUnique();

                    b.ToTable("trending_metrics", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("academic_identifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email_verification_token");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("email_verification_token_expires_at");

                    b.Property<string>("EvidenceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("evidence_url");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("Institution")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("institution");

                    b.Property<string>("InstitutionalEmail")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("institutional_email");

                    b.Property<string>("InstitutionalEmailVerificationToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("institutional_email_verification_token");

                    b.Property<DateTime?>("InstitutionalEmailVerificationTokenExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("institutional_email_verification_token_expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsInstitutionalEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_institutional_email_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("password_reset_token_expires_at");

                    b.Property<string>("ProgramOrField")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("program_or_field");

                    b.Property<string>("RequestedRole")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("requested_role");

                    b.Property<DateTime?>("ReviewRestrictedUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("review_restricted_until");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("VerificationReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("verification_reviewed_at");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("not_submitted")
                        .HasColumnName("verification_status");

                    b.Property<DateTime?>("VerificationSubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("verification_submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.AdminState", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.AdminSupportTicket", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Bookmark", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.Publication", "Publication")
                        .WithMany()
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificJournal.DataAccess.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Follow", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.User", "User")
                        .WithMany("Follows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Notification", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.Publication", "Publication")
                        .WithMany()
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScientificJournal.DataAccess.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Publication", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.Journal", "Journal")
                        .WithMany()
                        .HasForeignKey("JournalId");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationAuthor", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificJournal.DataAccess.Entities.Publication", "Publication")
                        .WithMany("PublicationAuthors")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationKeyword", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.Keyword", "Keyword")
                        .WithMany("PublicationKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificJournal.DataAccess.Entities.Publication", "Publication")
                        .WithMany("PublicationKeywords")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationReview", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationReviewModerationEvent", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.PublicationReview", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationReviewReport", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.User", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScientificJournal.DataAccess.Entities.PublicationReview", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReporterUser");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.PublicationVersion", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScientificJournal.DataAccess.Entities.Publication", "Publication")
                        .WithMany()
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.SyncLog", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.User", "TriggeredByUser")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TriggeredByUser");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.TrendingMetric", b =>
                {
                    b.HasOne("ScientificJournal.DataAccess.Entities.Keyword", "Keyword")
                        .WithMany("TrendingMetrics")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Keyword", b =>
                {
                    b.Navigation("PublicationKeywords");

                    b.Navigation("TrendingMetrics");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.Publication", b =>
                {
                    b.Navigation("PublicationAuthors");

                    b.Navigation("PublicationKeywords");
                });

            modelBuilder.Entity("ScientificJournal.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Follows");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
