<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ScientificJournal.DataAccess\ScientificJournal.DataAccess.csproj" />
    <ProjectReference Include="..\ScientificJournal.Common\ScientificJournal.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.6.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
