<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ScientificJournal.Common/ScientificJournal.Common.csproj" />
    <ProjectReference Include="../ScientificJournal.DataAccess/ScientificJournal.DataAccess.csproj" />
  </ItemGroup>
</Project>
